spring.datasource.url=jdbc:mysql://localhost:3306/Entos
spring.datasource.username=root
spring.datasource.password=aksahoo
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

file.upload.path=D:\\java\\code\\working project\\Enote-api-service\\estore\\src\\main\\resources\\static\\image
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=42MB

#Email send config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=spbangby28min@gmail.com
spring.mail.password=gnuc zqzz bygc cval  
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
